//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthTokenConfig) DeepCopyInto(out *OAuthTokenConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthTokenConfig.
func (in *OAuthTokenConfig) DeepCopy() *OAuthTokenConfig {
	if in == nil {
		return nil
	}
	out := new(OAuthTokenConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OAuthTokenConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthTokenConfigList) DeepCopyInto(out *OAuthTokenConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OAuthTokenConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthTokenConfigList.
func (in *OAuthTokenConfigList) DeepCopy() *OAuthTokenConfigList {
	if in == nil {
		return nil
	}
	out := new(OAuthTokenConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OAuthTokenConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthTokenConfigSpec) DeepCopyInto(out *OAuthTokenConfigSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	out.TargetSecretRef = in.TargetSecretRef
	if in.RefreshInterval != nil {
		in, out := &in.RefreshInterval, &out.RefreshInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthTokenConfigSpec.
func (in *OAuthTokenConfigSpec) DeepCopy() *OAuthTokenConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OAuthTokenConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthTokenConfigStatus) DeepCopyInto(out *OAuthTokenConfigStatus) {
	*out = *in
	in.LastRefreshed.DeepCopyInto(&out.LastRefreshed)
	in.NextRefresh.DeepCopyInto(&out.NextRefresh)
	in.ExpirationTime.DeepCopyInto(&out.ExpirationTime)
	in.RefreshExpiration.DeepCopyInto(&out.RefreshExpiration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthTokenConfigStatus.
func (in *OAuthTokenConfigStatus) DeepCopy() *OAuthTokenConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OAuthTokenConfigStatus)
	in.DeepCopyInto(out)
	return out
}
