apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "otto.fullname" . }}-manager-role
  labels:
  {{- include "otto.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.example.com
  resources:
  - oauthtokenconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.example.com
  resources:
  - oauthtokenconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - auth.example.com
  resources:
  - oauthtokenconfigs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "otto.fullname" . }}-manager-rolebinding
  labels:
  {{- include "otto.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "otto.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "otto.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
