apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "otto.fullname" . }}-oauthtokenconfig-editor-role
  labels:
  {{- include "otto.labels" . | nindent 4 }}
rules:
- apiGroups:
  - auth.example.com
  resources:
  - oauthtokenconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.example.com
  resources:
  - oauthtokenconfigs/status
  verbs:
  - get
