name: Release Charts

on:
  push:
    tags:
      - 'chart-v*.*.*'  # Match tags like chart-v1.2.3

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tag is on main branch
        run: |
          # Fetch the main branch to check if the tag is on it
          git fetch origin main
          # Check if the tag commit is part of the main branch
          if ! git merge-base --is-ancestor $GITHUB_SHA origin/main; then
            echo "Tag is not on the main branch. Exiting."
            exit 1
          fi

      - name: Change app version in Chart.yaml to latest tag
        run: |
          # Get the latest tag with semver format
          # This assumes tags are in the format vX.Y.Z
          latest_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          # Extract the version number from the tag
          version=${latest_tag#v}
          # Update the Chart.yaml file with the new version
          sed -i "s/^appVersion: .*/appVersion: $version/" dist/chart/Chart.yaml
      
      - name: Change chart version in Chart.yaml to latest tag
        run: |
          # Get the latest tag with semver format
          # This assumes tags are in the format chart-vX.Y.Z
          latest_tag=$(git tag --sort=-v:refname | grep -E '^chart-v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          # Extract the version number from the tag
          version=${latest_tag#chart-v}
          # Update the Chart.yaml file with the new version
          sed -i "s/^version: .*/version: $version/" dist/chart/Chart.yaml

      - name: Replace image tag in values.yaml with "latest"
        run: |
          # Replace the image tag in values.yaml with "latest"
          sed -i 's/tag: .*/tag: latest/' dist/chart/values.yaml

      - name: Replace image repository in values.yaml with "ghcr.io/winklermichael/otto"
        run: |
          # Replace the image repository in values.yaml with "ghcr.io/winklermichael/otto"
          sed -i 's/repository: .*/repository: ghcr.io\/winklermichael\/otto/' dist/chart/values.yaml

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: dist
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"