name: Release Application

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure tag is on main branch
        run: |
          # Fetch the main branch to check if the tag is on it
          git fetch origin main
          # Check if the tag commit is part of the main branch
          if ! git merge-base --is-ancestor $GITHUB_SHA origin/main; then
            echo "Tag is not on the main branch. Exiting."
            exit 1
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/otto:latest
            ghcr.io/${{ github.repository_owner }}/otto:${{ github.ref_name }}
