name: Release Application

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  packages: write
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure tag is on main branch
        run: |
          # Fetch the main branch to check if the tag is on it
          git fetch origin main
          # Check if the tag commit is part of the main branch
          if ! git merge-base --is-ancestor $GITHUB_SHA origin/main; then
            echo "Tag is not on the main branch. Exiting."
            exit 1
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/otto:latest
            ghcr.io/${{ github.repository_owner }}/otto:${{ github.ref_name }}

      - name: Extract changelog for this version
        id: changelog
        run: |
          # Extract the relevant section from CHANGELOG.md
          version="${GITHUB_REF##*/}" # Extract the tag name (e.g., v1.0.5)
          awk "/## \\[${version}\\]/ {flag=1; next} /## \\[/ {flag=0} flag" CHANGELOG.md > changelog_section.txt
          echo "changelog_body=$(cat changelog_section.txt)" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ env.changelog_body }}
          draft: false
          prerelease: false