name: Release Application

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - name: Check if tag is on main branch
        run: |
          # Fetch all refs to have main branch
          git fetch origin main
          if ! git merge-base --is-ancestor $GITHUB_SHA origin/main; then
            echo "Tag commit is not on main branch. Exiting."
            exit 1
          fi
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/otto:latest
            ghcr.io/${{ github.repository_owner }}/otto:${{ github.ref_name }}
      - name: Update Helm Chart appVersion
        run: |
          APP_VERSION=${GITHUB_REF#refs/tags/}
          yq e -i ".appVersion = \"${APP_VERSION}\"" charts/otto/Chart.yaml

      - name: Lint Helm Chart
        run: helm lint charts/otto

      - name: Package Helm Chart
        run: |
          helm package charts/otto --destination dist
          ls dist